services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    ports:
      - 9443:9443
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy_network" # Directs Traefik to hit the container on this interface
      - "traefik.http.routers.portainer.rule=Host(`portainer.home.local`)"
      - "traefik.http.routers.portainer.entrypoints=web,websecure"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000" # Internal container port
    networks:
      - default
      - proxy_network
networks:
  default:
    name: portainer_network
  proxy_network:
    external: true
